name = "cf-tg-bot"
main = "src/index.js"
compatibility_date = "2024-01-01"



[[d1_databases]]
binding = "DB" # å¿…é¡»æ˜¯ DBï¼Œä»£ç ä¸­å¼•ç”¨çš„æ˜¯è¿™ä¸ªåå­—
database_name = "tg-bot"
database_id = "95d33c2e-1568-4f1a-9d9a-95365e3f2aa9"


[[kv_namespaces]]
binding = "LIMIT_KV" # ä»£ç ä¸­ä½¿ç”¨çš„å˜é‡åï¼Œå¿…é¡»ä¸º LIMIT_KV
id = "556363f6ea01455682858741bade71e5" # ä½ åˆ›å»ºçš„ KV å‘½åç©ºé—´ ID



# 2. ç”Ÿäº§çŽ¯å¢ƒé…ç½®
[vars]
# é»˜è®¤ç®¡ç†å‘˜è´¦å·

# ä¼šè¯å¯†é’¥ï¼ˆå»ºè®®æ˜¯ä¸€ä¸²å¾ˆé•¿çš„éšæœºå­—ç¬¦ä¸²ï¼Œç”¨äºŽåŠ å¯† Cookieï¼‰
SESSION_SECRET = "super-secret-random-string-12345å–µå–µå–µðŸ³ï¸â€ðŸŒˆðŸ³ï¸â€âš§ï¸"

# æ³¨æ„ï¼šADMIN_PASSï¼ˆå¯†ç ï¼‰å±žäºŽæ•æ„Ÿä¿¡æ¯
# å¼ºçƒˆå»ºè®®ä¸è¦å†™åœ¨é…ç½®æ–‡ä»¶é‡Œï¼Œè€Œæ˜¯é€šè¿‡ Cloudflare æŽ§åˆ¶å°çš„ Settings -> Variables -> Secrets æ·»åŠ 
# æˆ–è€…ä½¿ç”¨å‘½ä»¤ï¼šwrangler secret put ADMIN_PASS